# Generated by Django 4.0 on 2023-09-09 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='lobbys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=0)),
                ('ueser1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_user1', to='auth.user')),
                ('ueser2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_user2', to='auth.user')),
            ],
        ),
    ]
